import random
#from test import testEqual

# The roll_dice function simulates the rolling of the dice. It
# creates a 2 dimensional list: each column is a die and each
# row is a throw. The function generates random numbers 1-6
# and puts them in the list.
def roll_dice(num_dice, num_rolls):

    # create a two-dimensional (num_dice by num_rolls) of zeros
    double_list = [[0 for i in range(num_dice)] for j in range(num_rolls)]

    # loop through each row and column, filling it with a random roll
    for roll in range(0, len(double_list)):
      for die in range(0, len(double_list[roll])):
          double_list[roll][die] = (int)(random.random()*6 + 1)

    return double_list


# This function takes a 2D list (which can be generated by roll_dice)
# and sums the value of all the dice in each row. It returns a 1
# dimensional list with the sum of each throw.
# Example:
# double_list: [[1, 5, 6],[2, 3, 1],[1, 3, 3]]
# sum_of_roll should return: [12, 6, 7]
def sum_of_roll(double_list):
    print(double_list)
    sum_value_in_list = []

    for value in double_list:
        sum_value_in_list.append(sum(value))

    return sum_value_in_list

# Bonus function! Takes a 2D list and returns
# the number of times a person rolls Yahtzee (all dice have
# the same value). Hint: you may want to create a helper
# function that takes individual rows of the list.
def yahtzee(double_list):

    match = "No Yahtzee :("

    for _dice in double_list:
        if check_dice(_dice) == 1:
            match = "Yahtzee!"

    return print(match)


def check_dice(_dice):

    for num in _dice:
        if num != _dice[0]:
            return 0

    return 1

# To play, yo'd do something like this
# dice = input("How many dice? ")
# rolls = input("What is the number of rolls? ")
# list = roll_dice(dice, rolls)
# print("Sum of roll: ", sum_of_roll(list))

dice = 3
rolls = 10
roll_list = roll_dice(dice, rolls)
print("Sum of roll: ", sum_of_roll(roll_list))

yahtzee(roll_list)
